### ISSUE TITLE
Warning: file_get_contents(../Resources/skeleton/bundle/bundle.mustache)

### ISSUE THREAD

**Issue by freeyland** [ruudy-es/Metronic-Bundle#2]
When doing:
php app/console ruudy:metronic:generate 
I get following error:
 [Symfony\Component\Debug\Exception\ContextErrorException]                                                                   
  Warning: file_get_contents(../Resources/skeleton/bundle/bundle.mustache): failed to open stream: No such file or directory

**Comment by ruudy-es** [comment]
Solved at https://github.com/ruudy-es/Metronic-Bundle/commit/8155edad85ae12ac1f9f52c653b2f86023285ced
